[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']

[tool.meson-python.args]
setup = ['-Ddocs=disabled', '-Dman=disabled']

[project]
name = "mididings"
description = 'A MIDI router/processor'
readme = "README.md"
requires-python = ">=3.9"
license-files = ["LICENSE.md", "LICENSES/*.txt",]
authors = [{name = "Dominic Sacré", email = "dominic.sacre@gmx.de"},]
maintainers = [{name = "George Rawlinson", email = "george@rawlinson.net.nz"},]
dependencies = ["decorator", "boost"]
classifiers = [
  "Topic :: Multimedia :: Sound/Audio :: MIDI",
  "Programming Language :: Python :: 3",
  "Development Status :: 5 - Production/Stable",
]
dynamic = ['version']  # Specify version string in top level meson.build

[project.optional-dependencies]
osc = ["pyliblo3",]
smf = ["pysmf",]
autorestart = ["pyinotify>=0.8",]
dbus = ["dbus-python",]
xdg = ["pyxdg",]
doc = ["sphinx", "sphinxcontrib-fulltoc", "furo",]
test = ["pytest",]

[project.urls]
homepage = "https://github.com/mididings/mididings"
documentation = "https://mididings.github.io/mididings/"
